export const USER_REGISTRATION = {
  REGISTER: "USER_REGISTRATION_REGISTER",
  SUCCESS: "USER_REGISTRATION_SUCCESS",
  FAIL: "USER_REGISTRATION_FAIL",
}

export const submit = (userInfo) => ({type: USER_REGISTRATION.REGISTER, userInfo })
